// <auto-generated />
using System;
using ClientDashboard_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientDashboard_API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250726212532_SeperateClientAndWorkoutData")]
    partial class SeperateClientAndWorkoutData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientDashboard_API.Entities.Client", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentBlockSession")
                        .HasColumnType("int");

                    b.Property<int?>("TotalBlockSessions")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("ClientDashboard_API.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentBlockSession")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<int?>("TotalBlockSessions")
                        .HasColumnType("int");

                    b.Property<string>("WorkoutTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientName");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("ClientDashboard_API.Entities.Workout", b =>
                {
                    b.HasOne("ClientDashboard_API.Entities.Client", "Client")
                        .WithMany("ClientWorkouts")
                        .HasForeignKey("ClientName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ClientDashboard_API.Entities.Client", b =>
                {
                    b.Navigation("ClientWorkouts");
                });
#pragma warning restore 612, 618
        }
    }
}
