// <auto-generated />
using System;
using ClientDashboard_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientDashboard_API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class ClientDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientDashboard_API.Entities.WorkoutData", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentBlockSession")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalBlockSessions")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Data");
                });
#pragma warning restore 612, 618
        }
    }
}
